// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioFlow.API.Data;

#nullable disable

namespace StudioFlow.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213145726_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("StudioFlow.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("StudioFlow.API.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact recording room for solo and duo sessions.",
                            HourlyRate = 45.00m,
                            Location = "Floor 1, Room A",
                            MaxCapacity = 3,
                            Name = "Red Studio"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mid-size room for podcasts and vocal groups.",
                            HourlyRate = 65.00m,
                            Location = "Floor 2, Room B",
                            MaxCapacity = 6,
                            Name = "Blue Studio"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Large multipurpose studio with isolation booth.",
                            HourlyRate = 90.00m,
                            Location = "Floor 3, Room C",
                            MaxCapacity = 10,
                            Name = "Green Studio"
                        });
                });

            modelBuilder.Entity("StudioFlow.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@studioflow.local",
                            FirstName = "Test",
                            LastName = "Manager",
                            PasswordHash = "$2a$11$SpRXyX1x1UB2Pwc6w9Qv/.jICpr2vR8M8h9Gw0L7N1Y1wD4xM7RLW",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 2, 13, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@studioflow.local",
                            FirstName = "Test",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$2fS8lktQm7f9m8Yx1Bdr9eV1LwxlHriB/9MUk8DJm9DB4UED9f9Hi",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 2, 13, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StudioFlow.API.Models.Booking", b =>
                {
                    b.HasOne("StudioFlow.API.Models.Studio", "Studio")
                        .WithMany("Bookings")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioFlow.API.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Studio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudioFlow.API.Models.Studio", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("StudioFlow.API.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
